### ISSUE TITLE
crash playing clip

### ISSUE THREAD

**Issue by CarlFK** [mltframework/shotcut#306]
```
shotcut-debian8-x86_64-160901.tar.bz2
```

tested on two machines (see end for specs), one seems fine, the other:
```
Failed to open BO for returned DRI2 buffer (1301x744, dri2 back buffer, named 111).
This is likely a bug in the X Server that will lead to a crash soon.
```
The input file is 45g, so can't exactly post it. 

After a while (same steps, different times of crash) 

00:03:42:29
00:01:09:53
00:11:20:18

```
GL error 0x502 at effect_chain.cpp:1660

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff9abfd700 (LWP 7349)]
0x00007ffff25c41c7 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt full
#0  0x00007ffff25c41c7 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 7328
        selftid = 7349
#1  0x00007ffff25c5e2a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7fffa66e7a40, 
            sa_sigaction = 0x7fffa66e7a40}, sa_mask = {__val = {1660, 0, 
              140734961969136, 140735507617424, 56249, 0, 140736587979855, 1, 
              140735408010936, 1, 140736587504800, 155306017423360, 
              2791897054, 0, 3, 140735789648736}}, sa_flags = -1503645440, 
          sa_restorer = 0x7fff89f05690}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fffa668732e in movit::EffectChain::render_to_fbo(unsigned int, unsigned int, unsigned int) ()
   from /home/carl/local/Shotcut/Shotcut.app/lib/libmovit.so.2
No symbol table info available.
#3  0x00007fffa695642f in GlslManager::render_frame_texture (this=0x1087b80, 
    chain=0x7fff88517690, frame=0x7fff6adf52e0, width=1280, height=720, 
    image=0x7fff9abfcda8) at filter_glsl_manager.cpp:404
        texture = 0x7fff89f05690
        fbo = 56249
        sync = <optimized out>
#4  0x00007fffa6959043 in convert_image (frame=0x7fff6adf52e0, 
    image=0x7fff9abfcda8, format=0x6ff3a2c, 
    output_format=mlt_image_glsl_texture) at filter_movit_convert.cpp:573
        leaf_service = <optimized out>
        chain = 0x7fff88517610
        glsl = <optimized out>
        properties = 0x7fff6adf52e0
        error = 0
        width = 1280
---Type <return> to continue, or q <return> to quit---
        height = 720
#5  0x00007ffff7657718 in mlt_frame_get_image (self=0x7fff6adf52e0, 
    buffer=0x7fff9abfcda8, format=0x6ff3a2c, width=0x7fff9abfcd94, 
    height=0x7fff9abfcd98, writable=0) at mlt_frame.c:591
        properties = 0x7fff6adf52e0
        get_image = 0x7fffa695cb40
     <get_image(mlt_frame, uint8_t**, mlt_image_format*, int*, int*, int)>
        requested_format = <optimized out>
        error = <optimized out>
#6  0x00007ffff766a578 in consumer_read_ahead_thread (arg=0x1ca0)
    at mlt_consumer.c:897
        priv = 0x6ff3a20
        width = 1280
        height = 720
        preview_off = 117389896
        preview_format = 40787
        samples = 801
        audio = 0x7fff882db390
        buffer = 26
        frame = 0x7fff6adf52e0
        image = 0x7050060 "`"
        ante = {tv_sec = 1472769866, tv_usec = 641818}
#7  0x00000000004951cd in Mlt::RenderThread::run() ()
No symbol table info available.
#8  0x00007ffff375e399 in ?? ()
   from /home/carl/local/Shotcut/Shotcut.app/lib/libQt5Core.so.5
No symbol table info available.
#9  0x00007ffff32016aa in start_thread (arg=0x7fff9abfd700)
    at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fff9abfd700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140735789651712, 
---Type <return> to continue, or q <return> to quit---
                -5200064009465692645, 0, 140735798041055, 140735789652416, 
                117389856, 5200140424999665179, 5200055673753894427}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#10 0x00007ffff269613d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
(gdb) 
```

I see this too:
```
[Debug  ] <MLT> [consumer sdl_audio] dropped video frame 21466
[Debug  ] <MLT> [consumer sdl_audio] dropped video frame 21467
[Debug  ] <MLT> [consumer sdl_audio] too many frames dropped - forcing next frame
[Debug  ] <MLT> [consumer sdl_audio] dropped video frame 21468
[Debug  ] <MLT> [consumer sdl_audio] dropped video frame 21469
```
and I see  'dropped video frame 21469"  for all frames starting at 1.

crashes on:
```
model name	: Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz
Linux twist 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
LENOVO ThinkPad Twist 33476LU
Description:	Ubuntu 15.10
Codename:	wily
```

seems to be ok on:
```
model name	: Intel(R) Core(TM) i5 CPU       M 540  @ 2.53GHz
Linux dc10b 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Hewlett-Packard HP EliteBook 2540p
Description:	Ubuntu 16.04.1 LTS
Codename:	xenial
```

**Comment by ddennedy** [comment]
You are using GPU processing on an incompatible system.
