### ISSUE TITLE
Crashes on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [mltframework/shotcut#340]
While trying to create the FreeBSD port, I can't get past this crash:
```
(gdb) bt
#0  __je_arena_mapbits_get (chunk=0x807400000, pageind=<optimized out>) at /usr/src/lib/libc/../../contrib/jemalloc/include/jemalloc/internal/arena.h:806
#1  __je_arena_mapbits_binind_get (chunk=0x807400000, pageind=<optimized out>) at /usr/src/lib/libc/../../contrib/jemalloc/include/jemalloc/internal/arena.h:863
#2  __je_arena_salloc (demote=false, tsdn=<optimized out>, ptr=<optimized out>) at /usr/src/lib/libc/../../contrib/jemalloc/include/jemalloc/internal/arena.h:1384
#3  __je_isalloc (demote=false, tsdn=<optimized out>, ptr=<optimized out>) at /usr/src/lib/libc/../../contrib/jemalloc/include/jemalloc/internal/jemalloc_internal.h:951
#4  ifree (tsd=<optimized out>, ptr=<optimized out>, tcache=<optimized out>, slow_path=<optimized out>) at jemalloc_jemalloc.c:1810
#5  0x00000008081bf13e in __free (ptr=0x8074a69b0 <QListData::shared_null>) at jemalloc_jemalloc.c:1937
#6  0x0000000806ebfa64 in ?? () from /usr/local/lib/libQt5Core.so.5
#7  0x0000000806f2ea29 in QRegExp::indexIn(QString const&, int, QRegExp::CaretMode) const () from /usr/local/lib/libQt5Core.so.5
#8  0x0000000806f3c582 in QString::replace(QRegExp const&, QString const&) () from /usr/local/lib/libQt5Core.so.5
#9  0x000000000065b51d in AbstractStringAppender::stripFunctionName (name=0x6672fe "Mlt::Controller::Controller()") at src/AbstractStringAppender.cpp:47
#10 0x000000000065c0f9 in AbstractStringAppender::formattedString (this=0x81136dc60, timeStamp=..., logLevel=Logger::Debug, file=0x6672ec "mltcontroller.cpp", line=53, func
tion=0x6672fe "Mlt::Controller::Controller()", message=...) at src/AbstractStringAppender.cpp:137
#11 0x000000000065cc10 in FileAppender::append (this=0x81136dc60, timeStamp=..., logLevel=Logger::Debug, file=0x6672ec "mltcontroller.cpp", line=53, function=0x6672fe "Mlt:
:Controller::Controller()", message=...) at src/FileAppender.cpp:76
```

Replacing malloc library with google perftools yields this:
```
[Debug  ] <Mlt::Controller::Controller()> begin 
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x8076a69b0 
```

It looks like you might have some memory corruption.

Version 16.11

**Comment by ddennedy** [comment]
You are in your own for FreeBSD.

**Comment by yurivict** [comment]
What does this mean?

**Comment by yurivict** [comment]
You don't want to fix bugs? Thanks, great attitude, keep going that way!

**Comment by ddennedy** [comment]
It means I assume you want help by submitting a bug report. No one on the team can help you with FreeBSD. You can submit a patch or pull request.

**Comment by yurivict** [comment]
Memory corruption has nothing to do with FreeBSD, it was only spotted there.
