### ISSUE TITLE
version 15.06.01 crashes on Linux Mint 17.1 (64 bit version)

### ISSUE THREAD

**Issue by johanneswilm** [mltframework/shotcut#86]
To reproduce:

1. Download https://github.com/mltframework/shotcut/releases/download/v15.06/shotcut-debian7-x86_64-150601.tar.bz2
2. Execute Shotcut
3. Under "Timeline" click hamburger menu and "Add Video Track"
4. Click on tab "Program"
5. Segmentation fault

**Comment by metellius** [comment]
Confirmed on my end. BT:
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000045a6cd in ?? ()
(gdb) bt
#0  0x000000000045a6cd in ?? ()
#1  0x0000000000572824 in ?? ()
#2  0x00007ffff4e84341 in QMetaObject::activate(QObject*, int, int, void**) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Core.so.5
#3  0x00007ffff63db5b1 in QTabBar::tabBarClicked(int) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Widgets.so.5
#4  0x00007ffff63e4fcf in QTabBar::mousePressEvent(QMouseEvent*) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Widgets.so.5
#5  0x00007ffff6273bfd in QWidget::event(QEvent*) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Widgets.so.5
#6  0x00007ffff63e52fa in QTabBar::event(QEvent*) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Widgets.so.5
#7  0x00007ffff623bf34 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Widgets.so.5
#8  0x00007ffff623f336 in QApplication::notify(QObject*, QEvent*) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Widgets.so.5
#9  0x00007ffff4e5b554 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Core.so.5
#10 0x00007ffff623e38a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Widgets.so.5
#11 0x00007ffff62936a5 in ?? () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Widgets.so.5
#12 0x00007ffff62959e8 in ?? () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Widgets.so.5
#13 0x00007ffff623bf34 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Widgets.so.5
#14 0x00007ffff623f50e in QApplication::notify(QObject*, QEvent*) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Widgets.so.5
#15 0x00007ffff4e5b554 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Core.so.5
#16 0x00007ffff5388981 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Gui.so.5
#17 0x00007ffff5389205 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Gui.so.5
#18 0x00007ffff5370ae8 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Gui.so.5
#19 0x00007fffe8d26fd0 in ?? () from /home/harald/Qt/5.2.0/gcc_64/plugins/platforms/libqxcb.so
#20 0x00007ffff0ae8c5d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff0ae8f48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff0ae8ffc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff4eabfc4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Core.so.5
#24 0x00007ffff4e5a2cb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Core.so.5
#25 0x00007ffff4e5e33e in QCoreApplication::exec() () from /home/harald/Qt/5.2.0/gcc_64/lib/libQt5Core.so.5
#26 0x000000000043cd04 in ?? ()
#27 0x00007ffff3b4fec5 in __libc_start_main (main=0x43cb10, argc=1, argv=0x7fffffffd788, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffd778) at libc-start.c:287
#28 0x000000000043d1a7 in ?? ()

```
This looks a lot like a qt bug, we should see if it's still in 5.5.
