### ISSUE TITLE
Consistent crash in mlt_service_connect_producer

### ISSUE THREAD

**Issue by samth** [mltframework/shotcut#896]
I consistently get a crash when I drag a video to the timeline. This happens immediately, on the first attempt to put anything on the timeline. 

Here's the backtrace from the crash in GDB:

```
Thread 1 "shotcut" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f6778f in mlt_service_connect_producer () from /usr/lib/x86_64-linux-gnu/libmlt.so.6
(gdb) where
#0  0x00007ffff7f6778f in mlt_service_connect_producer () from /usr/lib/x86_64-linux-gnu/libmlt.so.6
#1  0x00007ffff7f713bd in mlt_transition_connect () from /usr/lib/x86_64-linux-gnu/libmlt.so.6
#2  0x00007ffff7f71cfa in mlt_field_plant_transition () from /usr/lib/x86_64-linux-gnu/libmlt.so.6
#3  0x00005555556f8ea4 in ?? ()
#4  0x00005555556f7229 in ?? ()
#5  0x00005555556f799a in ?? ()
#6  0x000055555571a944 in ?? ()
#7  0x00007ffff7cf5d8a in QUndoStack::push(QUndoCommand*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00005555556ffcbd in ?? ()
#9  0x00005555557942fc in ?? ()
#10 0x0000555555794b93 in ?? ()
#11 0x00007ffff69dbf65 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#12 0x00007ffff68cadad in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#13 0x00007ffff68cd1e4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#14 0x00007ffff68ce1d1 in QV4::QObjectMethod::callInternal(QV4::Value const*, QV4::Value const*, int) const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#15 0x00007ffff68eb401 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#16 0x00007ffff68ed2c7 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#17 0x00007ffff687b1a0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#18 0x00007ffff68eb401 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#19 0x00007ffff68ed2c7 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#20 0x00007ffff687a64f in QV4::Function::call(QV4::Value const*, QV4::Value const*, int, QV4::ExecutionContext const*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#21 0x00007ffff6a04587 in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#22 0x00007ffff69a338c in QQmlBoundSignalExpression::evaluate(void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#23 0x00007ffff69a4528 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#24 0x00007ffff69e774d in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#25 0x00007ffff6983715 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#26 0x00007ffff6217bd3 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff760259c in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#28 0x00007ffff7534ad8 in QQuickItem::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#29 0x00007ffff795fa66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff79690f0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007ffff61ec93a in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff75529b0 in QQuickWindowPrivate::deliverDragEvent(QQuickDragGrabber*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#33 0x00007ffff75533ca in QQuickWindow::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#34 0x00007ffff79a22b6 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff7e9fce3 in QQuickWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5
#36 0x00007ffff795fa66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007ffff79697aa in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
```

Here's the output from Shotcut prior to the crash:

```
[Info   ] <MainWindow::open> "/home/samth/Videos/c211-test/c211-test.mlt" 
[New Thread 0x7fffa892d700 (LWP 49096)]
[New Thread 0x7fff809b8700 (LWP 49097)]
[New Thread 0x7fff7bfff700 (LWP 49098)]
[New Thread 0x7fff7affc700 (LWP 49099)]
[Info   ] <MLT> [consumer sdl2_audio] Audio Opened: driver=pulseaudio channels=2 frequency=48000
[swscaler @ 0x7fff94006380] YUV color matrix differs for YUV->YUV, using intermediate RGB to convert
[Debug  ] <MainWindow::open> "/home/samth/2020-07-31 23-27-29.mp4" 
[Debug  ] <MltXmlChecker::check> begin 
[Debug  ] <MltXmlChecker::check> end 
[h264 @ 0x555555e44840] Reinit context to 1920x1088, pix_fmt: yuv420p
[h264 @ 0x555558610dc0] Reinit context to 1920x1088, pix_fmt: yuv420p
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55555861f1c0] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[h264 @ 0x555558610180] Reinit context to 1920x1088, pix_fmt: yuv420p
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[AVIOContext @ 0x555557dd6580] Statistics: 201769 bytes read, 2 seeks
[AVIOContext @ 0x555557eba840] Statistics: 201769 bytes read, 2 seeks
[AVIOContext @ 0x555557ecee40] Statistics: 201769 bytes read, 2 seeks
[Debug  ] <Mlt::Controller::setPreviewScale> 1920 x 1080 
[Debug  ] <MainWindow::setAudioChannels> 2 
[Debug  ] <Mlt::Controller::setAudioChannels> 2 
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55555863a280] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[h264 @ 0x555558644100] Reinit context to 1920x1088, pix_fmt: yuv420p
[h264 @ 0x555558c7f280] Reinit context to 1920x1088, pix_fmt: yuv420p
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x555558ca5700] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[h264 @ 0x555558c80e80] Reinit context to 1920x1088, pix_fmt: yuv420p
[AVIOContext @ 0x555558643140] Statistics: 201769 bytes read, 2 seeks
[Debug  ] <MLT> [producer avformat-novalidate] "/home/samth/2020-07-31 23-27-29.mp4" checking VFR: pkt.duration 3000
[h264 @ 0x555558d3a900] Reinit context to 1920x1088, pix_fmt: yuv420p
[Info   ] <MLT> [filter swresample] 2(stereo) s16 44100Hz -> 2(stereo) s16 48000Hz
[Info   ] <MainWindow::open> "/home/samth/2020-07-31 23-27-29.mp4" 
[h264 @ 0x555558d3a900] Reinit context to 1920x1088, pix_fmt: yuv420p
[Debug  ] <TimelineDock::dragEnterEvent> true 
[Debug  ] <Timeline::OverwriteCommand::redo> trackIndex 0 position 0 
```

The video in question was recorded in OBS on the same machine. Other videos I've tried produce the same segfault, in the same function. The machine is a Dell XPS 13 with a hi-DPI display, running Ubuntu 20.04. I have Shotcut 20.02.21.

**Comment by ddennedy** [comment]
You are not using a build provided by us, so I am not supporting it. See our download page. Why do people make a build they do not test or use is beyond me.

**Comment by ddennedy** [comment]
Same as https://forum.shotcut.org/t/shotcut-crashes-on-ubuntu-when-i-drag-images-into-the-timeline/19998/4

**Comment by samth** [comment]
Yes, thanks. I installed the snap and it's working.

**Comment by ddennedy** [comment]
Btw do you have Frei0r plugins installed from your package repos? Maybe they did not add that dependency.

**Comment by ddennedy** [comment]
It would have been nice to have confirmation that this is the source of the problem, but I am confident that Shotcut will have serious problems if the frei0r plugins including those dependent upon cairographics are not installed. So, I added a check for that on startup for the next version. Here is hoping that helps distro package users 351993d7e4c765d28d1a27f2e8a009a682fde8d7
