### ISSUE TITLE
Shotcut crashes when moving the separator between video display and timeline up and down

### ISSUE THREAD

**Issue by lvml** [mltframework/shotcut#90]
Hi,

first let me say that I tried Shotcut for the first time today.
I've been using kdenlive for years, but now that kdenlive does not compile without the whole KDE 5 infrastructure anymore, I thought it would be time to try Shotcut, and given its early development state, I really like what I've seen so far.

I compiled Shotcut from the git master today. I also compiled Qt 5.4.2 / mlt / ffmpeg  and all other dependencies not readily available under CentOS 7.1 from their respective current source repository head.

I currently experience frequent crashes, especially reproduceable when moving the horizontal separator line between the (upper) video display and the (lower) timeline up and down. Such movement causes crashes after seconds.

Here's what gdb "bt" says at the point of the crash:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffdc2b9924 in pushbuf_kref () from /lib64/libdrm_nouveau.so.2
(gdb) bt
#0  0x00007fffdc2b9924 in pushbuf_kref () from /lib64/libdrm_nouveau.so.2
#1  0x00007fffdc2b9f59 in pushbuf_validate () from /lib64/libdrm_nouveau.so.2
#2  0x00007fffddb54355 in nv50_state_validate () from /usr/lib64/dri/nouveau_dri.so
#3  0x00007fffddb5fa68 in nv50_draw_vbo () from /usr/lib64/dri/nouveau_dri.so
#4  0x00007fffddcd4cf3 in st_draw_vbo () from /usr/lib64/dri/nouveau_dri.so
#5  0x00007fffddca6ac3 in vbo_handle_primitive_restart () from /usr/lib64/dri/nouveau_dri.so
#6  0x00007fffddca7e63 in vbo_validated_drawrangeelements () from /usr/lib64/dri/nouveau_dri.so
#7  0x00007fffddca83a3 in vbo_exec_DrawElements () from /usr/lib64/dri/nouveau_dri.so
#8  0x00007ffff6d28f80 in QSGBatchRenderer::Renderer::renderMergedBatch(QSGBatchRenderer::Batch const*) () from /tmp/applink/kdenlive/lib/libQt5Quick.so.5
#9  0x00007ffff6d2a7fd in QSGBatchRenderer::Renderer::renderBatches() () from /tmp/applink/kdenlive/lib/libQt5Quick.so.5
#10 0x00007ffff6d30b2b in QSGBatchRenderer::Renderer::render() () from /tmp/applink/kdenlive/lib/libQt5Quick.so.5
#11 0x00007ffff6d3b214 in QSGRenderer::renderScene(QSGBindable const&) () from /tmp/applink/kdenlive/lib/libQt5Quick.so.5
#12 0x00007ffff6d3b65b in QSGRenderer::renderScene(unsigned int) () from /tmp/applink/kdenlive/lib/libQt5Quick.so.5
#13 0x00007ffff6d48bde in QSGRenderContext::renderNextFrame(QSGRenderer*, unsigned int) () from /tmp/applink/kdenlive/lib/libQt5Quick.so.5
#14 0x00007ffff6d918a4 in QQuickWindowPrivate::renderSceneGraph(QSize const&) () from /tmp/applink/kdenlive/lib/libQt5Quick.so.5
#15 0x00007ffff6d636b6 in ?? () from /tmp/applink/kdenlive/lib/libQt5Quick.so.5
#16 0x00007ffff6d640a5 in ?? () from /tmp/applink/kdenlive/lib/libQt5Quick.so.5
#17 0x00007ffff712f7bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/applink/kdenlive/lib/libQt5Widgets.so.5
#18 0x00007ffff7134620 in QApplication::notify(QObject*, QEvent*) () from /tmp/applink/kdenlive/lib/libQt5Widgets.so.5
#19 0x00007ffff39fd025 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /tmp/applink/kdenlive/lib/libQt5Core.so.5
#20 0x00007ffff3a539ad in QTimerInfoList::activateTimers() () from /tmp/applink/kdenlive/lib/libQt5Core.so.5
#21 0x00007ffff3a53dd1 in ?? () from /tmp/applink/kdenlive/lib/libQt5Core.so.5
#22 0x00007fffefe6e99a in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#23 0x00007fffefe6ece8 in g_main_context_iterate.isra.24 () from /lib64/libglib-2.0.so.0
#24 0x00007fffefe6ed9c in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#25 0x00007ffff3a5409c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/applink/kdenlive/lib/libQt5Core.so.5
#26 0x00007ffff39faf8b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/applink/kdenlive/lib/libQt5Core.so.5
#27 0x00007ffff3a025c6 in QCoreApplication::exec() () from /tmp/applink/kdenlive/lib/libQt5Core.so.5
#28 0x000000000043f162 in ?? ()
#29 0x00007ffff273aaf5 in __libc_start_main () from /lib64/libc.so.6
#30 0x000000000043f599 in ?? ()
```
(Don't wonder about the "/tmp/applink/kdenlive/..." paths - this is in fact the --prefix I installed Shotcut and its dependencies to.)

I also see suspicous messages, sometimes only in "dmesg", sometimes also emitted in the terminal window I start Shotcut from:

```
[348901.541477] nouveau E[shotcut[13946]] push 1 buffer not in list
[348902.813029] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF IN
[348902.813040] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF 003201d1 203e5d00 00000000 04000432
[348902.813044] nouveau E[  PGRAPH][0000:04:00.0] ch 4 [0x003f92b000 shotcut[13946]] subc 5 class 0x5039 mthd 0x0310 data 0x40c50000
[348902.813053] nouveau E[     PFB][0000:04:00.0] trapped read at 0x0020370000 on channel 0x0003f92b [shotcut[13946]] PGRAPH/DISPATCH/M2M_IN reason: PAGE_NOT_PRESENT
[348902.813070] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF NOTIFY
[348902.813075] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF 00304041 00000000 00000000 06000000
[348902.813077] nouveau E[  PGRAPH][0000:04:00.0] ch 4 [0x003f92b000 shotcut[13946]] subc 5 class 0x5039 mthd 0x023c data 0x00000000
[348902.813085] nouveau E[     PFB][0000:04:00.0] trapped read at 0x0000000000 on channel 0x0003f92b [shotcut[13946]] PGRAPH/DISPATCH/M2M_IN reason: NULL_DMAOBJ
[348902.813094] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF IN
[348902.813099] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF 00320051 00000040 00000000 04000000
[348902.813101] nouveau E[  PGRAPH][0000:04:00.0] ch 4 [0x003f92b000 shotcut[13946]] subc 5 class 0x5039 mthd 0x023c data 0x00000000
[348902.813108] nouveau E[     PFB][0000:04:00.0] trapped read at 0x0000000000 on channel 0x0003f92b [shotcut[13946]] PGRAPH/DISPATCH/M2M_IN reason: NULL_DMAOBJ
[348902.813118] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF IN
[348902.813123] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF 00320051 00000040 00000000 04000000
[348902.813125] nouveau E[  PGRAPH][0000:04:00.0] ch 4 [0x003f92b000 shotcut[13946]] subc 5 class 0x5039 mthd 0x023c data 0x00000000
[348902.813132] nouveau E[     PFB][0000:04:00.0] trapped read at 0x0000000000 on channel 0x0003f92b [shotcut[13946]] PGRAPH/DISPATCH/M2M_IN reason: NULL_DMAOBJ
[348902.813150] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF IN
[348902.813154] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF 003200d1 00000040 00000000 04000000
[348902.813157] nouveau E[  PGRAPH][0000:04:00.0] ch 4 [0x003f92b000 shotcut[13946]] subc 5 class 0x5039 mthd 0x023c data 0x00000000
[348902.813164] nouveau E[     PFB][0000:04:00.0] trapped read at 0x0000000000 on channel 0x0003f92b [shotcut[13946]] PGRAPH/DISPATCH/M2M_IN reason: NULL_DMAOBJ
[348902.813173] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF IN
[348902.813177] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF 003200d1 00000040 00000000 04000000
[348902.813180] nouveau E[  PGRAPH][0000:04:00.0] ch 4 [0x003f92b000 shotcut[13946]] subc 5 class 0x5039 mthd 0x023c data 0x00000000
[348902.813187] nouveau E[     PFB][0000:04:00.0] trapped read at 0x0000000000 on channel 0x0003f92b [shotcut[13946]] PGRAPH/DISPATCH/M2M_IN reason: NULL_DMAOBJ
[348902.813196] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF IN
[348902.813200] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF 003200d1 00000040 00000000 04000000
[348902.813202] nouveau E[  PGRAPH][0000:04:00.0] ch 4 [0x003f92b000 shotcut[13946]] subc 5 class 0x5039 mthd 0x023c data 0x00000000
[348902.813210] nouveau E[     PFB][0000:04:00.0] trapped read at 0x0000000000 on channel 0x0003f92b [shotcut[13946]] PGRAPH/DISPATCH/M2M_IN reason: NULL_DMAOBJ
[348902.813219] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF IN
[348902.813223] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF 00320051 00000040 00000000 04000000
[348902.813225] nouveau E[  PGRAPH][0000:04:00.0] ch 4 [0x003f92b000 shotcut[13946]] subc 5 class 0x5039 mthd 0x023c data 0x00000000
[348902.813233] nouveau E[     PFB][0000:04:00.0] trapped read at 0x0000000000 on channel 0x0003f92b [shotcut[13946]] PGRAPH/DISPATCH/M2M_IN reason: NULL_DMAOBJ
[348902.813242] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF IN
[348902.813246] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF 00320051 00000040 00000000 04000000
[348902.813248] nouveau E[  PGRAPH][0000:04:00.0] ch 4 [0x003f92b000 shotcut[13946]] subc 5 class 0x5039 mthd 0x023c data 0x00000000
[348902.813255] nouveau E[     PFB][0000:04:00.0] trapped read at 0x0000000000 on channel 0x0003f92b [shotcut[13946]] PGRAPH/DISPATCH/M2M_IN reason: NULL_DMAOBJ
[348902.813265] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF IN
[348902.813269] nouveau E[  PGRAPH][0000:04:00.0] TRAP_M2MF 00320151 00000140 00000000 04000000
[348902.813271] nouveau E[  PGRAPH][0000:04:00.0] ch 4 [0x003f92b000 shotcut[13946]] subc 5 class 0x5039 mthd 0x0328 data 0x00000000
[348902.882311] nouveau E[shotcut[13946]] Unknown handle 0x00000022
[348902.882320] nouveau E[shotcut[13946]] validate_init
[348902.882322] nouveau E[shotcut[13946]] validate: -2
[348902.944988] nouveau E[shotcut[13946]] Unknown handle 0x00000015
[348902.945002] nouveau E[shotcut[13946]] validate_init
[348902.945004] nouveau E[shotcut[13946]] validate: -2
[348903.491167] nouveau E[shotcut[13946]] Unknown handle 0x0000001c
[348903.491174] nouveau E[shotcut[13946]] validate_init
[348903.491176] nouveau E[shotcut[13946]] validate: -2
```

I did not enable the "experimental GUI support".

The nouveau kernel driver is from the vanilla linux-4.1 in use, the GPU is a nvida 8800 GT. (I cannot use the proprietary nvidia driver, because their "legacy" drivers are not compatible with contemporary Linux kernels anymore.)

Here's information on the OS-supplied library versions involved in the crash:
```
 rpm -qif /lib64/libdrm_nouveau.so.2
Name        : libdrm
Version     : 2.4.56
Release     : 2.el7
Architecture: x86_64
Install Date: Sat 06 Jun 2015 03:10:23 PM CEST
Group       : System Environment/Libraries
Size        : 294971
License     : MIT
Signature   : RSA/SHA256, Sat 14 Mar 2015 09:00:45 AM CET, Key ID 24c6a8a7f4a80eb5
Source RPM  : libdrm-2.4.56-2.el7.src.rpm
Build Date  : Fri 06 Mar 2015 04:16:56 AM CET
Build Host  : worker1.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Vendor      : CentOS
URL         : http://dri.sourceforge.net
Summary     : Direct Rendering Manager runtime library
Description :
Direct Rendering Manager runtime library
```

```
rpm -qif /usr/lib64/dri/nouveau_dri.so
Name        : mesa-dri-drivers
Version     : 10.2.7
Release     : 5.20140910.el7
Architecture: x86_64
Install Date: Sat 06 Jun 2015 03:15:15 PM CEST
Group       : User Interface/X Hardware Support
Size        : 35476279
License     : MIT
Signature   : RSA/SHA256, Sat 14 Mar 2015 09:16:40 AM CET, Key ID 24c6a8a7f4a80eb5
Source RPM  : mesa-10.2.7-5.20140910.el7.src.rpm
Build Date  : Fri 06 Mar 2015 07:24:20 AM CET
Build Host  : worker1.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Vendor      : CentOS
URL         : http://www.mesa3d.org
Summary     : Mesa-based DRI drivers
Description :
Mesa-based DRI drivers.
```

Any idea what's going wrong, here?

**Comment by ddennedy** [comment]
Shotcut is only developed, tested, and supported on Qt 5.2 at this time. We hope to move onto Qt 5.5 next as that includes a bug-fix we provided. Looking at your messages, Shotcut makes heavy usage of Qt Quick, which uses OpenGL, and it appears to be a problem between Qt and nouveau. There are not even any Shotcut functions in that backtrace! Closing this as not-my-bug and not a supported version.

Please feel free to debug it further on your own. In particular, you could try building and running some Qt Quick examples from Qt Creator or SDK to see how stable they are on your system w/ nouveau. However, bear in mind that Shotcut uses a combination of Qt Widgets (traditional GUI), Qt Quick, and some custom GL code for the video display. That is a supported combination, but it is not well represented in the examples collection.
