### ISSUE TITLE
20.11.28 segfault when loading .mlt file

### ISSUE THREAD

**Issue by fenugrec** [mltframework/shotcut#979]
Hi,
I created an empty project, saved, and closed shotcut.
When I try to reopen the .mlt file (attached , renamed to [yt.txt](https://github.com/mltframework/shotcut/files/5689694/yt.txt) )
shotcut instantly segfaults. 
I don't have a debugging build atm but the stack trace looks like this :

```
#0  0x00007ffff61588a7 in QObject::setProperty(char const*, QVariant const&) ()
    at /usr/lib/libQt5Core.so.5
#1  0x000055555571a4f0 in  ()
#2  0x00007ffff6159e00 in  () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff6159e00 in  () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff758543e in QQuickRenderControl::initialize(QOpenGLContext*) ()
    at /usr/lib/libQt5Quick.so.5
#5  0x00007ffff7ebe6e5 in QQuickWidget::resizeEvent(QResizeEvent*) ()
    at /usr/lib/libQt5QuickWidgets.so.5
#6  0x00007ffff79b959e in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff7977752 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff6122a6a in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#9  0x00007ffff79b0810 in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) ()
    at /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff79b076b in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) ()
    at /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff79b076b in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) ()
    at /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff79b076b in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) ()
    at /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff79b076b in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) ()
    at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff79b076b in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) ()
    at /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff79b5619 in QWidgetPrivate::prepareToRender(QRegion const&, QFlags<QWidget::RenderFlag>) () at /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff79b5cf5 in QWidget::render(QPainter*, QPoint const&, QRegion const&, QFlags<QWidget::RenderFlag>) () at /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff79b62f9 in QWidget::render(QPaintDevice*, QPoint const&, QRegion const&, QFlags<QWidget::RenderFlag>) () at /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff79b6531 in  () at /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff7d14bd4 in QGraphicsEffectSource::pixmap(Qt::CoordinateSystem, QPoint*, QGraphicsEffect::PixmapPadMode) const () at /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff7d14d7a in QGraphicsEffect::sourcePixmap(Qt::CoordinateSystem, QPoint*, QGraphicsEffect::PixmapPadMode) const () at /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff7d153d6 in QGraphicsOpacityEffect::draw(QPainter*) () at /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff79b1ba8 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
    at /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff79b2520 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff79b0e6d in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff79b2520 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/libQt5Widgets.so.5
#26 0x00007ffff79b0e6d in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/libQt5Widgets.so.5
#27 0x00007ffff79b2520 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/libQt5Widgets.so.5
#28 0x00007ffff79b0e6d in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/libQt5Widgets.so.5
#29 0x00007ffff798831c in  () at /usr/lib/libQt5Widgets.so.5
#30 0x00007ffff79b925b in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#31 0x00007ffff7977752 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#32 0x00007ffff6122a6a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#33 0x00007ffff6125563 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#34 0x00007ffff617c094 in  () at /usr/lib/libQt5Core.so.5
#35 0x00007ffff4aa18f4 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#36 0x00007ffff4af5821 in  () at /usr/lib/libglib-2.0.so.0
#37 0x00007ffff4aa0121 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#38 0x00007ffff617b6d1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#39 0x00007ffff61213ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#40 0x00007ffff6129884 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#41 0x00005555555dda34 in main ()
```

distro : arch linux x86_64
shotcut 20.11.28
qt5-base 5.15.2

Let me know if I can provide further info.

**Comment by fenugrec** [comment]
bleh, I recompiled and the issue is gone. Probably something wrong in my distro's package, I need to check again before I close this.

**Comment by ddennedy** [comment]
I did not reproduce it using on of our builds. We only support our own builds.
